// Code generated by protoc-gen-go. DO NOT EDIT.
// source: awesome.proto

/*
Package awesome is a generated protocol buffer package.

It is generated from these files:
	awesome.proto

It has these top-level messages:
	EchoRequest
	EchoResponse
*/
package awesome

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EchoRequest struct {
	Ping string `protobuf:"bytes,1,opt,name=ping" json:"ping,omitempty"`
}

func (m *EchoRequest) Reset()                    { *m = EchoRequest{} }
func (m *EchoRequest) String() string            { return proto.CompactTextString(m) }
func (*EchoRequest) ProtoMessage()               {}
func (*EchoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *EchoRequest) GetPing() string {
	if m != nil {
		return m.Ping
	}
	return ""
}

type EchoResponse struct {
	Pong string `protobuf:"bytes,1,opt,name=pong" json:"pong,omitempty"`
}

func (m *EchoResponse) Reset()                    { *m = EchoResponse{} }
func (m *EchoResponse) String() string            { return proto.CompactTextString(m) }
func (*EchoResponse) ProtoMessage()               {}
func (*EchoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *EchoResponse) GetPong() string {
	if m != nil {
		return m.Pong
	}
	return ""
}

func init() {
	proto.RegisterType((*EchoRequest)(nil), "awesome.EchoRequest")
	proto.RegisterType((*EchoResponse)(nil), "awesome.EchoResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Awesome service

type AwesomeClient interface {
	Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error)
}

type awesomeClient struct {
	cc *grpc.ClientConn
}

func NewAwesomeClient(cc *grpc.ClientConn) AwesomeClient {
	return &awesomeClient{cc}
}

func (c *awesomeClient) Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	out := new(EchoResponse)
	err := grpc.Invoke(ctx, "/awesome.Awesome/Echo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Awesome service

type AwesomeServer interface {
	Echo(context.Context, *EchoRequest) (*EchoResponse, error)
}

func RegisterAwesomeServer(s *grpc.Server, srv AwesomeServer) {
	s.RegisterService(&_Awesome_serviceDesc, srv)
}

func _Awesome_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AwesomeServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/awesome.Awesome/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AwesomeServer).Echo(ctx, req.(*EchoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Awesome_serviceDesc = grpc.ServiceDesc{
	ServiceName: "awesome.Awesome",
	HandlerType: (*AwesomeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _Awesome_Echo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "awesome.proto",
}

func init() { proto.RegisterFile("awesome.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 129 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x2c, 0x4f, 0x2d,
	0xce, 0xcf, 0x4d, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0x14, 0xb9,
	0xb8, 0x5d, 0x93, 0x33, 0xf2, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x84, 0xb8, 0x58,
	0x0a, 0x32, 0xf3, 0xd2, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x25, 0x25, 0x2e,
	0x1e, 0x88, 0x92, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0xb0, 0x9a, 0x7c, 0x24, 0x35, 0xf9, 0x79,
	0xe9, 0x46, 0x0e, 0x5c, 0xec, 0x8e, 0x10, 0x13, 0x85, 0x4c, 0xb9, 0x58, 0x40, 0xca, 0x85, 0x44,
	0xf4, 0x60, 0x56, 0x22, 0x59, 0x20, 0x25, 0x8a, 0x26, 0x0a, 0x31, 0x53, 0x89, 0x21, 0x89, 0x0d,
	0xec, 0x30, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf8, 0xf8, 0xb3, 0xc2, 0xa9, 0x00, 0x00,
	0x00,
}
